# Generated by Django 4.0.1 on 2022-10-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=18)),
                ('Name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='000000000000000000', max_length=18)),
                ('user_name', models.CharField(default='DEFAULT', max_length=18)),
                ('message_count', models.CharField(default='0', max_length=18)),
                ('interactions', models.CharField(default='0', max_length=18)),
                ('twitch_addiction', models.CharField(default='0', max_length=18)),
                ('gender', models.CharField(default='Not Set', max_length=100)),
                ('pronouns', models.CharField(default='Not Set', max_length=100)),
                ('parent_server', models.ForeignKey(blank=True, default='000000000000000000', on_delete=django.db.models.deletion.CASCADE, to='login.server')),
            ],
        ),
    ]
